// <auto-generated />
namespace SecureFrameworkDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _04_Encryption : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_04_Encryption));
        
        string IMigrationMetadata.Id
        {
            get { return "201612140253401_04_Encryption"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
