// <auto-generated />
namespace BuildSecureSystems.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _02_AddedRLS : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_02_AddedRLS));
        
        string IMigrationMetadata.Id
        {
            get { return "201612060340181_02_AddedRLS"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
