// <auto-generated />
namespace Talk_BuildSecureSystems_RowLevelSecurity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _01_AddedOrders : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_01_AddedOrders));
        
        string IMigrationMetadata.Id
        {
            get { return "201612050339403_01_AddedOrders"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
